InstaClone/core/urls.py
from django.urls import path
from core.views import (
    HomeView,
    FollowDoneView,
    UnfollowDoneView,
    PostCreatView,
    PostDeleteView,
    PostDetailView,
    PostLikeView,
    PostUnlikeView,
    PostCommentView,
    PostSaveView,
    PostUnsaveView,
    LikedPostsView,
    ExplorePostsView,
    SavedPostsView,
    )
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('feed/', login_required(HomeView.as_view()), name='home_feed_view'),

    # follow and unfollow view
    path('follow/done/', login_required(FollowDoneView.as_view()), name='follow_done_view'),
    path('unfollow/done/', login_required(UnfollowDoneView.as_view()), name='unfollow_done_view'),

    # post related urls
    path('post/<int:id>/', login_required(PostDetailView.as_view()), name='post_detail_view'),
    path('post/create/', login_required(PostCreatView.as_view()), name='post_create_view'),
    path('post/delete/<int:id>/', login_required(PostDeleteView.as_view()), name='post_delete_view'),
    path('post/save/<int:id>/', login_required(PostSaveView.as_view()), name='post_save_view'),
    path('post/unsave/<int:id>/', login_required(PostUnsaveView.as_view()), name='post_unsave_view'),
    
    path('post/liked/', login_required(LikedPostsView.as_view()), name='liked_posts_view'),
    path('post/saved/', login_required(SavedPostsView.as_view()), name='saved_posts_view'),
    path('post/explore/', login_required(ExplorePostsView.as_view()), name='explore_posts_view'),

    path('post/like/<int:id>/', PostLikeView.as_view(), name='post_like_view'),
    path('post/unlike/<int:id>/', PostUnlikeView.as_view(), name='post_unlike_view'),
    path('post/comment/<int:id>/', PostCommentView.as_view(), name='post_comment_view'),
]

InstaClone/insta_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('core.urls')),
    path('', include('user.urls')),
]

urlpatterns.extend(
    static(
        settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT
        )
    )

InstaClone/user/urls.py
from django.urls import path
from user.views import (
    ProfileView,
    ProfileEditView,
    AllProfilesView,
    )
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path(
        'in/<str:username>/', 
        login_required(ProfileView.as_view()), 
        name='profile_view'
        ),
    path(
        'in/<str:username>/edit/', 
        login_required(ProfileEditView.as_view()), 
        name='profile_edit_view'
        ),
    path(
        'profiles/', 
        login_required(AllProfilesView.as_view()), 
        name='all_profiles_view'
        ),
]

InstaClone/core/models.py
from django.db import models
from django.contrib.auth import get_user_model

from core.utils import auto_save_current_user
# Create your models here.

User = get_user_model()


# Posts Model
class Post(models.Model):
    # id = models.AutoField(primary_key=True)     # generated by default 
    text = models.CharField(max_length=140, blank=True, null=True)  # null == None, blank = ''
    image = models.ImageField(upload_to='post_images')   # BASE_DIR -> media -> post_images
    user = models.ForeignKey(User, on_delete=models.PROTECT, editable=False)    # user_id
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return str(self.pk)

    def save(self, *args, **kwargs):
        auto_save_current_user(self)
        super(Post, self).save(*args, **kwargs)

    @property
    def likes_count(self):
        count = self.like_set.count()
        return count

    @property
    def comments_count(self):
        count = self.comment_set.count()
        return count


# Comments Model
class Comment(models.Model):
    text = models.CharField(max_length=240)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)
    commented_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text

    def save(self, *args, **kwargs):
        auto_save_current_user(self)
        super(Comment, self).save(*args, **kwargs)

# Likes Model
class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)
    liked_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.post.id)

    def save(self, *args, **kwargs):
        auto_save_current_user(self)
        super(Like, self).save(*args, **kwargs)

# Followers Model
class Follow(models.Model):
    user = models.ForeignKey(User, related_name='follow_follower', on_delete=models.CASCADE, editable=False)
    followed = models.ForeignKey(User, related_name='follow_followed', on_delete=models.CASCADE)
    followed_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f"{self.user} --> {self.followed}"

    def save(self, *args, **kwargs):
        auto_save_current_user(self)
        super(Follow, self).save(*args, **kwargs)


class SavedPost(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, editable=False)
    saved_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.post.pk)

    def save(self, *args, **kwargs):
        auto_save_current_user(self)
        super(SavedPost, self).save(*args, **kwargs)

InstaClone/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from user.managers import CustomUserManager
# Create your models here.


GENDER_CHOICES = [
    ('M', 'Male'),
    ('F', 'Female'),
    ('None', 'Prefer not to say.'),
]


class User(AbstractUser):
    picture = models.ImageField(upload_to='profile_pictures', null=True, blank=True)
    full_name = models.CharField(max_length=100, help_text='Help people discover your account by using the name you\'re known by: either your full name, nickname, or business name.')
    email = models.EmailField(unique=True)

    # Optional fields
    bio = models.TextField(null=True, blank=True, help_text='Provide your personal information, even if the account is used for a business, a pet or something else. This won\'t be a part of your public profile.')
    website = models.URLField(null=True, blank=True)
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, null=True, blank=True)
    is_private_account = models.BooleanField(null=True, blank=True)

    first_name = None
    last_name = None

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name','username',]

    objects = CustomUserManager()

    def __str__(self):
        return self.email

    @property
    def follower_count(self):
        count = self.follow_followed.count()
        return count

    @property
    def following_count(self):
        count = self.follow_follower.count()
        return count

    @property
    def posts_count(self):
        count = self.post_set.count()
        return count

InstaClone/user/forms.py
from django.contrib.auth import get_user_model
from django import forms


User = get_user_model()

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'picture',
            'full_name',
            'username',
            'email',
            'bio',
            'website',
            'phone_number',
            'gender',
            'is_private_account',
            )
        labels = {
            'is_private_account': 'Do you want to make your account private ?',
            'phone_number': 'Phone'
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            if field == 'picture':
                self.fields[field].widget.attrs.update({'class': 'form-control-file'})
            elif field == 'is_private_account':
                self.fields[field].widget.attrs.update({'class': 'form-check-input'})
            else:
                self.fields[field].widget.attrs.update({'class': 'form-control form-control-sm'})

InstaClone/user/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.http import HttpResponse
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.db.models import Q

from user.forms import UserEditForm
from core.models import Follow
# Create your views here.

User = get_user_model()

class ProfileView(View):
    template_name_anon = 'user/anonymous_profile.html'
    template_name_auth = 'user/authenticated_profile.html'

    def get(self, request, *args, **kwargs):
        username = kwargs.get('username')

        try:
            user = User.objects.get(username=username)
        except Exception as e:
            return HttpResponse('<h1>This page does not exist.</h1>')

        
        if username == request.user.username:
            context = { 'user': user }
            return render(request, self.template_name_auth, context=context)
        else:
            try:
                Follow.objects.get(user=request.user, followed=user)
                is_follows_this_user = True
            except Exception as e:
                is_follows_this_user = False
                    
            context = { 'user': user, 'is_follows_this_user': is_follows_this_user }
            return render(request, self.template_name_anon, context=context)


class ProfileEditView(View):
    template_name = 'user/profile_edit.html'
    form_class = UserEditForm

    def get(self, request, *args, **kwargs):
        username = kwargs.get('username')

        if username != request.user.username:
            return HttpResponse('<h1>This page does not exist.</h1>')

        form = self.form_class(instance=request.user)
        context = {'form': form}
        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES, instance=request.user)

        if form.is_valid():
            form.save()
            messages.success(request, 'Saved your details in a safe place.')
            return redirect('profile_edit_view', request.user.username)
        else:
            for field in form.errors:
                form[field].field.widget.attrs['class'] += ' is-invalid'
            context = {'form': form}
            return render(request, self.template_name, context=context)


class AllProfilesView(View):
    template_name = 'user/all_profiles.html'

    def get(self, request, *args, **kwargs):
        search_term = request.GET.get('query')

        if search_term:
            all_profiles = User.objects.filter(
                    Q(username__contains=search_term) | Q(full_name__contains=search_term)
                ).exclude(
                    username=request.user.username
                )
        else:
            all_profiles = User.objects.none()

        context = {'all_profiles': all_profiles}
        return render(request, self.template_name, context=context)

InstaClone/templates/user/all_profiles.html
{% extends 'core/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/user/all_profiles.css' %}">
{% endblock %}

{% block content %}
    <div class="container py-5">
        <div class="row">
            <div class="col-12 col-md-8 card offset-md-2">
                {% if all_profiles %}

                    <!-- All User Profiles -->
                    {% for user in all_profiles %}

                    <!-- Single user Profile Row -->
                    <a href="{% url 'profile_view' user.username %}" class="text-decoration-none">
                        <div class="row py-3 px-5 border-bottom">

                            <!-- Profile picture -->
                            {% if user.picture %}
                                <img src="/media/{{ user.picture }}" class="rounded-circle z-depth-0 profile__pic">
                            {% else %}
                                <img src="https://i.pinimg.com/originals/51/f6/fb/51f6fb256629fc755b8870c801092942.png"  class="profile__pic rounded-circle z-depth-0">
                            {% endif %}
                            <!-- Profile picture end -->

                            <div class="d-flex mx-4">

                                <!-- User's full name -->
                                <p class="m-auto">{{ user.full_name }}</p>
                                
                            </div>
                            <div class="ml-auto">
                                <button class="btn btn-sm btn-primary mx-2" type="submit">Profile</button>
                            </div>
                        </div>
                    </a>
                    <!-- Single user Profile Row end -->

                    {% endfor %}
                    <!-- All User Profiles end -->

                {% else %}

                    <!-- No Results found -->
                    <p class="justify-content-center text-center mx-auto my-5">No Results to display</p>

                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

InstaClone/templates/user/authenticated_profile.html
{% extends 'core/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/user/profile.css' %}">
{% endblock %}

{% block content %}
    <div class="container py-5">
        <div class="row mb-5 pl-md-5">
            <div class="col-12 col-md-3 d-flex justify-content-center">
                <label for="upload_profile_pic" class="profile__pic__btn">

                    <!-- Profile Picture -->
                    {% if user.picture %}
                        <a href="{% url 'profile_edit_view' request.user.username %}">
                            <img src="{{ user.picture.url }}" class="profile__pic">
                        </a>
                    {% else %}
                        <img src="https://i.pinimg.com/originals/51/f6/fb/51f6fb256629fc755b8870c801092942.png"  class="profile__pic">
                    {% endif %}
                    <!-- Profile Picture end -->

                </label>
            </div>
            <div class="col-12 col-md-9 pl-5">

                <div class="row userprofile__row__first py-2">

                    <!-- Username -->
                    <h2 class="username__text mr-4">{{ user.username }}</h2>

                    <!-- Edit Profile Button -->
                    <a class="edit__profile__btn mx-3 mx-md-4 text-decoration-none text-reset px-2 py-1" href="{% url 'profile_edit_view' request.user.username %}">Edit Profile</a>

                    <!-- Settings icon -->
                    <a class="text-decoration-none text-reset settings__icon d-flex justify-content-center" data-toggle="modal" data-target="#settings_list">
                        <span class="fa fa-cog mx-3 mx-md-4"></span>
                    </a>

                </div>
                
                <div class="row userprofile__row__stats py-2">
                    <span class="mr-3 mr-md-5">

                        <!-- Total number of posts -->
                        <strong>
                        {{ request.user.posts_count }}
                        </strong> posts

                    </span>
                    <span class="mr-3 mr-md-5">

                        <!-- Total number of followers -->
                        <strong>
                        {{ request.user.follower_count }}
                        </strong> followers

                    </span>
                    <span class="mr-3 mr-md-5">

                        <!-- Total followings count -->
                        <strong>
                        {{ request.user.following_count }}
                        </strong> following

                    </span>
                </div>
                <div class="row user__fullname py-2">
                    <span class="col-12 px-0">

                        <!-- User fullname -->
                        <strong>{{ user.full_name }}</strong>

                    </span>

                    <!-- User's Bio if any -->
                    {% if user.bio %}
                        <span class="col-12 px-0">
                            {{ user.bio }}
                        </span>
                    {% endif %}

                    <!-- User's website if any -->
                    {% if user.website %}
                        <span class="col-12 px-0">
                            <strong><a href="{{ user.website }}">{{ user.website }}</a></strong>
                        </span>
                    {% endif %}

                </div>
            </div>
        </div>
        <div class="row pt-3">
            <div class="col-12">
                <nav>
                    <div class="nav nav-tabs justify-content-center" id="nav-tab" role="tablist">
                        
                        <!-- All my posts tab -->
                        <a class="nav-item nav-link active text-reset" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Posts</a>
                        
                        <!-- All saved posts tab -->
                        <a class="nav-item nav-link text-reset" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Saved</a>

                    </div>
                </nav>
                <div class="tab-content" id="nav-tabContent">

                    <!-- All my posts tab content -->
                    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                        
                    {% if request.user.posts_count != 0 %}
                        <!-- All posts grids -->
                        <div class="all__posts__grid row justify-content-center">
                            
                        {% for post in request.user.post_set.all %}
                            <!-- Single posts grid -->
                            <div class='card p-0 col-12 col-md-4 col-lg-3 my-4 mx-3'>
                                <a href="{% url 'post_detail_view' post.pk %}" class="text-decoration-none text-reset">

                                    <!-- Post image -->
                                    <img src="{{ post.image.url }}" class="w-100 img-fluid" style="height: 230px;object-fit: cover;">

                                    <div class='posts__likes__comment mx-auto py-3 text-center text-mute row justify-content-center' style="font-size: 14px;">
                                        <span class="mx-2">
                                            <span class="far fa-heart"></span>

                                            <!-- total post like count -->
                                            {{ post.likes_count }}

                                        </span> 
                                        <span class="mx-2">
                                            <span class="far fa-comment"></span>

                                            <!-- total post comment count -->
                                            {{ post.comments_count }}

                                        </span>
                                        <span class="mx-2">

                                            <!-- post delete button -->
                                            <a data-toggle="modal" data-target="#post_delete_{{ post.pk }}" style="cursor: pointer;">
                                                <span class="fa fa-trash"></span>
                                            </a>
                                            
                                        </span>
                                    </div>
                                </a>
                            </div>
                            <!-- Single posts grid end -->

                            <!-- Post Delete modal -->
                            <div class="modal fade" id="post_delete_{{ post.pk }}" tabindex="-1" aria-labelledby="post_delete_{{ post.pk }}_label" aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered">
                                    <div class="modal-content">
                                        <div class="modal-body p-0 py-2 text-center">
                                            <div class="p-1 m-0 px-4">
                                                <p>Do you really want to delete this post?</p>
                                            </div>
                                            <div class="p-1 m-0 px-4">
                                                <form method="POST" action="{% url 'post_delete_view' post.pk %}">
                                                    {% csrf_token %}
                                                    <button class="btn btn-sm btn-warning" type="submit">Yes</button>
                                                    <a class="btn btn-sm btn-info" data-dismiss="modal">No</a>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- Post Delete modal end -->
                        {% endfor %}

                        </div>
                        <!-- All posts grid end -->

                    {% else %}

                        <!-- No posts images -->
                        <div class="no__posts__img">
                            <img src="{% static 'img/no-posts1.jpg' %}">
                            <img src="{% static 'img/no-posts2.jpg' %}">
                        </div>

                    {% endif %}

                    </div>
                    <!-- All my posts tab content end -->

                    <!-- Saved posts tab content -->
                    <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                        <div class="all__posts__grid row justify-content-center">
                        {% for savedpost_obj in request.user.savedpost_set.all %}
                            {% with post=savedpost_obj.post %}
                            <div class='card p-0 col-12 col-md-4 col-lg-3 my-4 mx-3'>
                                <a href="{% url 'post_detail_view' post.pk %}" class="text-decoration-none text-reset">
                                    <img src="{{ post.image.url }}" class="w-100 img-fluid" style="height: 230px;object-fit: cover;">
                                    <div class='posts__likes__comment mx-auto py-3 text-center text-mute row justify-content-center' style="font-size: 14px;">
                                        <span class="mx-2">
                                            <span class="far fa-heart"></span>

                                            <!-- total like count -->
                                            {{ post.likes_count }}

                                        </span> 
                                        <span class="mx-2">
                                            <span class="far fa-comment"></span>

                                            <!-- total comment count -->
                                            {{ post.comments_count }}

                                        </span>           
                                    </div>
                                </a>
                            </div>
                            {% endwith %}
                        {% endfor %}
                        </div>
                    </div>
                    <!-- Saved posts tab content end -->

                </div>                
            </div>
        </div>
    </div>


    <!-- All Modals in this page -->

    <!-- Settings Modal -->
    <div class="modal fade" id="settings_list" tabindex="-1" aria-labelledby="settings_list_label" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body p-0 py-2 text-center">

                    <!-- Edit Profile Button -->
                    <div class="p-1 m-0 px-4">
                        <a href="{% url 'profile_edit_view' request.user.username %}" class="text-reset text-decoration-none">Edit Profile</a>
                    </div>
                    <!-- Edit Profile Button end -->

                    <div class="dropdown-divider"></div>

                    <!-- Change password button -->
                    <div class="p-1 m-0 px-4">
                        <a href="{% url 'password_change_view' %}" class="text-reset text-decoration-none">Change Password</a>
                    </div>
                    <!-- Change password button end -->

                    <div class="dropdown-divider"></div>

                    <div class="p-1 m-0 px-4">

                    <!-- Signout button -->
                    <form method="POST" action="{% url 'signout_view' %}">
                        {% csrf_token %}
                        <a href="javascript:;" onclick="parentNode.submit();" class="text-reset text-decoration-none">Sign Out</a>
                    </form>
                    <!-- Signout button end -->

                    </div>

                    <div class="dropdown-divider"></div>

                    <div class="p-1 m-0 px-4">
                        <a data-dismiss="modal" style="cursor: pointer;">Cancel</a>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- Settings Modal end -->

{% endblock %}

InstaClone/templates/user/profile_edit.html
{% extends 'core/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/user/profile_edit.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 my-4">

                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-primary" role="alert">
                          {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}

                <div class="card profile__edit__card m-auto">
                    <div class="card-header">
                        <p class="m-0" style="color: #5f5f5f;">Edit Profile</p>
                    </div>
                    <div class="card-body offset-md-2">

                        <!-- User's Profile Picture -->
                        {% if request.user.picture %}
                        <div>
                            <img src="{{ request.user.picture.url }}" class="rounded-circle z-depth-0 offset-md-2 mb-4" style="height: 100px;width: 100px">
                        </div>
                        {% else %}
                            <img src="https://i.pinimg.com/originals/51/f6/fb/51f6fb256629fc755b8870c801092942.png"  class="rounded-circle z-depth-0 offset-md-2 mb-4" style="height: 100px;width: 100px">
                        {% endif %}
                        <!-- User's Profile Picture end -->

                        <!-- Profile Edit form -->
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}

                            {% for field in form %}
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label col-form-label-sm text-md-right font-weight-bolder" for="{{ field.auto_id }}">{{ field.label }}</label>
                                <div class="col-sm-8">
                                    {{ field }}
                                    <small id="passwordHelpBlock" class="form-text text-muted">
                                        {{ field.help_text }}
                                    </small>
                                    <div class="invalid-feedback">
                                        {{ field.errors }}
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                            <div class="offset-md-2 my-1">
                                <button class="btn btn-sm btn-primary">Submit</button>
                            </div>
                        </form>
                        <!-- Profile Edit form end -->

                    </div>                    
                </div>
            </div>
        </div>
    </div>
{% endblock %}